#exclude:
#- sass
baseurl: /

title: Ритуал

# Задаем дефолтные настройки для плагина постраничного вывода постов: jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 2

# Подключаем плагин: jekyll-paginate-v2
gem:
  -jekyll-paginate-v2

plugins:
  - jekyll-feed

menu:
  - url: /
    name: Главная
  - url: /gallery/
    name: Галерея
  - url: /about/
    name: О нас
  - url: /contacts/
    name: Контакты

sass:
  sass_dir: /assets/styles