#exclude:
#- sass
baseurl: /

title: Ритуал

menu:
  - url: /
    name: Главная
  - url: /gallery/
    name: Галерея
  - url: /about/
    name: О нас
  - url: /contacts/
    name: Контакты

sass:
  sass_dir: /assets/styles